### ISSUE TITLE
Is there a way to animate rate property?

### ISSUE THREAD

**Issue by DavydLiu** [skywinder/GaugeKit#17]
Such as using `UIViewAnimationCurveEaseInOut` to animate `rate`.

**Comment by skywinder** [comment]
Since `UIViewAnimationCurveEaseInOut` works with `UIView`'s, and Gauges built on `CALayer`'s I believe it's not possible.

But according this: http://stackoverflow.com/a/4134510/1698467

```
[CATransaction setAnimationTimingFunction:[CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseInEaseOut]];
```

I think it could be done as option. It will nice feature to implement in next releases.

**Comment by skywinder** [comment]
@DavydLiu Did you found a solution?

**Comment by francisadelante** [comment]
Hi Im trying to animate the rate is there a way to do this? this my code 

UIView.animateWithDuration(2, delay: 1, options: .CurveEaseInOut, animations: { () -> Void in
                  &nbsp; &nbsp;         let converResultToCGFloat = CGFloat(result!)
                   &nbsp; &nbsp;       cell.gauge.rate = converResultToCGFloat
                   &nbsp; &nbsp;         cell.gauge.layoutIfNeeded()
                           }, completion: nil)

but the only animation I made with this code is move my gauge towards top not really making animation in gauge rate. Do you guys have a way to do gauge rate animation?

**Comment by dylandepass** [comment]
I was able to make it work using INTUAnimationEngine.

INTUAnimationEngine.animateWithDuration(2.0, delay: 0, easing: INTUEaseOutSine, animations: { (percent) -> Void in
    var value = percent \* 100;
    if(value < finalRate){
        self.gauge.rate = value
    }
}, completion: nil);

There must be a way to do it natively without a third party library, but this works for now.

**Comment by jetstar89** [comment]
Pls try to add animation to ringLayer for key path: "strokeEnd", this should work.

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
