### ISSUE TITLE
Change Color programmatically for dynamically created gauge.

### ISSUE THREAD

**Issue by francisadelante** [skywinder/GaugeKit#18]
Hi I am displaying the gauge in CellForRowAtIndexPath and I tried changing the color of gauge depending on its value this is my actual code of doing it 

 if result! > 0 && result! < 26 {
     cell.gauge.startColor = UIColor.redColor()
     cell.gauge.endColor = UIColor.redColor()
} else if result! > 25 && result! < 51 {
     cell.gauge.startColor = UIColor.orangeColor()
     cell.gauge.endColor = UIColor.orangeColor()
} else if result! > 50 && result < 76 {
    cell.gauge.startColor = UIColor.yellowColor()
    cell.gauge.endColor = UIColor.yellowColor()
} else {
    cell.gauge.startColor = UIColor.greenColor()
    cell.gauge.endColor = UIColor.greenColor()
 }

but it doesn't seem to work it keeps displaying the color i set in mainStoryBoard. The `if condition` works fine it reads the code in each scenario but it doesn't render the color I need.

**Comment by skywinder** [comment]
Hi. I tried to change color and it works. You can try it by yourself by clonning this repo and switch to  branch `change-color-test`

**Comment by skywinder** [comment]
@francisadelante Ok, got it. It works for `GaugeType` = `Circle` But not works for half gauges left and right.

**Comment by francisadelante** [comment]
I am using half gauge I forgot to mention.Thanks for quick support.

**Comment by skywinder** [comment]
Fixed in `0.2.4`!

**Comment by francisadelante** [comment]
I have it use the 0.2.4 version it is now working fine. Thank you so much

**Comment by skywinder** [comment]
You're welcome! :)
Don't forget to put your app on wiki page
https://github.com/skywinder/GaugeKit/wiki/Apps-using-GaugeKit :wink:

**Comment by francisadelante** [comment]
Sure I will. :)
