### ISSUE TITLE
Add ability to add gradient colors for Circle gauge.

### ISSUE THREAD

**Issue by skywinder** [skywinder/GaugeKit#2]
It's subtask of  #12.

I start working on it in `gradientCircle` branch, but implementation is not quite easy and still have issues.

Also - it looks not very well without overlapping (the border of `startColor` and `endColor`). 
I want to find solution, that can fix this and #12 issue at once.
![screen shot 2015-08-03 at 09 29 08](https://cloud.githubusercontent.com/assets/3356474/9031963/7dc90da0-39c2-11e5-85b5-5239e5db1733.png)

**Comment by gsapienza** [comment]
Just copy this from the GaugeHalf file into the same spot in the GaugeCircle one:

if ringGradientLayer == nil {
            ringGradientLayer = CAGradientLayer()
            if isCircle && (layer.bounds.width < layer.bounds.height) {
                let adjust: CGFloat = (layer.bounds.height - layer.bounds.width) / 2 / layer.bounds.height
                ringGradientLayer.startPoint = CGPointMake(0.5, 1 - adjust)
                ringGradientLayer.endPoint = CGPointMake(0.5, adjust)
            } else {
                ringGradientLayer.startPoint = CGPointMake(0.5, 1)
                ringGradientLayer.endPoint = CGPointMake(0.5, 0)
            }
            ringGradientLayer.colors = [startColor.CGColor, endColor.CGColor]
            ringGradientLayer.frame = layer.bounds
            ringGradientLayer.mask = ringLayer
            gaugeLayer.addSublayer(ringGradientLayer)
        }

**Comment by DrAma999** [comment]
Hello Skywinder, I love your project. I also went into the same problem, but for time reason I used a masked image.  It doesn't seem possible to create a circular gradient using CG, but you can fake it(somehow) thinking in small linear gradients, the idea has found proof of its possibility in that SO answer http://stackoverflow.com/questions/24751607/fill-circular-ring-with-gradient-color-according-to-percentage

**Comment by skywinder** [comment]
@DrAma999 thanks for the link. I will take a look on this solution

**Comment by NickPappas** [comment]
Any solution yet? Subscribing to this.

**Comment by skywinder** [comment]
Hi, @NickPappas. As you can see on screenshot - it does not looks well without overlaping. So, as soon as https://github.com/skywinder/GaugeKit/issues/12 closed - it will be easy not implement this feature also.

**Comment by DrAma999** [comment]
Hi, This guy made this class to draw gradients, maybe you can get in touch with him https://github.com/maxkonovalov/MKGradientView

**Comment by skywinder** [comment]
@DrAma999 Thanks! 3rd gradient looks like what I want to get.
Actually I already implement it in `gradientCircle` branch. You can see it on screenshot above. I just need to implement infinite option for this circles. But thanks for the link!  :+1:

**Comment by skywinder** [comment]
@sinanulkuatam let's continue https://github.com/skywinder/GaugeKit/pull/32#issuecomment-219742392 here:
As I said there is branch `gradientCircle`. I'm not work in this direction last time in case of lack of time. But I you know how to implement it right - I would be glad to review PR 😉

**Comment by sinanku** [comment]
Check it out :) https://github.com/skywinder/GaugeKit/pull/35

![gradient](https://cloud.githubusercontent.com/assets/1269987/15362259/a9ef4e90-1ce2-11e6-9438-252f98290138.gif)

**Comment by saiidabs** [comment]
@sinanku  how did u get the circular view to work like that?

**Comment by sinanku** [comment]
@saiidabs originally I made @IBInspectables to change gradient properties, after I just made it so that you defined a start color and end color that was already a part of the library.  You can download my fork and run the example project, it should help get you on the right track.

**Comment by skywinder** [comment]
thnks, @sinanku! would you like to make a PR to this project?

**Comment by skywinder** [comment]
already implemented in latest versions
