### ISSUE TITLE
it would be possible to activate gesture directly on the gauge?

### ISSUE THREAD

**Issue by ZoeVale** [skywinder/GaugeKit#21]
Hi, for my personal project i need to activate gesture directly on the gauge like a normal slider.
It's possible?
Thank you very much for any response.

**Comment by skywinder** [comment]
Hi. It would be a nice feature, but it's not implemented yet.

**Comment by skywinder** [comment]
I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍
