### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by blueheronlabs** [skywinder/GaugeKit#23]
in CAShapeLayer+oval.swift

add:
import UIKit
import QuartzCore

**Comment by skywinder** [comment]
Thanks!
Hmm, this error in Swift 2.0? Whichversion of Xcode? Can't reproduce it.

**Comment by blueheronlabs** [comment]
Yes:  Swift 2.0, Xcode 7.0.1 (7A1001)

I am not using CocoaPods, Carthage, or git submodule.  :(
I added the GaugeKit files manually to my Swift project in Xcode.

**Comment by skywinder** [comment]
Great! Thanks for info!

**Comment by skywinder** [comment]
Closing, since there is no any other occurrences and we go with Swift 3 anyway 🎉
