### ISSUE TITLE
Question: App Store Review

### ISSUE THREAD

**Issue by gsach** [skywinder/GaugeKit#25]
Have you uploaded an App to the App Store with the success using Gauges similar to Activity app? I was wondering if the gauge in the second example (which looks pretty similar to the Activity native app) could be reject by Apple for mimicking iOS behaviour.

**Comment by skywinder** [comment]
It depends, what your app doing. If it will mimic native activity app without any additional features - they will reject app. If you will implement your own functionality - I can't see any problems to use it.

The style, that you add to gauges - is up to you. 
You can change whatever you want.
I just show in this example, that it's possible to reproduce Apple's gauges as well.
