### ISSUE TITLE
UIAppearance not supported

### ISSUE THREAD

**Issue by nikita-leonov** [skywinder/GaugeKit#31]
Component's architecture biased to a design through Interface Builder or directly in code. There is another way of defining visual style of components which is UIAppearance. I know at least several projects where defying style directly in code and in IB is prohibited by architectural conventions. Supporting all standard ways of customization may potentially increase adoption for a component.

**Comment by skywinder** [comment]
@nikita-leonov Thanks for recommendation. 
I never tried befre to adopt my own class to `UIAppearance` protocol.
Seems that, that I need is implement 

```
static func appearance() -> Self
AND
static func appearanceForTraitCollection(_ trait: UITraitCollection) -> Self
```

I will consider that proposal and try to adopt Gauge class to this protocol. Thanks!

**Comment by skywinder** [comment]
I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍
