### ISSUE TITLE
iOS 10 Beta Support

### ISSUE THREAD

**Issue by sdevo619** [skywinder/GaugeKit#37]
Hi,
I would really like to use GuageKit in an upcoming project, as it will make my life much easier in designing some cool gauges. Tried importing it into my new project and there are 56 errors, mostly related to changes Apple made in Swift 3. Do you have plans on updating GuageKit for iOS 10? Is there any plans for GuageKit on WatchOS 3? Do you have a version you are testing for iOS 10 Beta, that I may be able to get access to early? Thank you very much in advance. I have been looking all over for this type of Pod, and this helps a lot, assuming you plan to update it for iOS10.

**Comment by skywinder** [comment]
Hi. new version in master works on Swift 3 already hooray!!

**Comment by ghost** [comment]
Hey there @skywinder I'm attempting to use with cocoapods in a swift 3 project but it's only letting me install 0.3.2. Trying to get 0.4.0 throws an error. I see its in the podspec but no dice. Any idea?

**Comment by skywinder** [comment]
@druidithius can you sent me error, that throws during installation process?

**Comment by ghost** [comment]
This is the error thrown by cocoapods:

[!] Unable to satisfy the following requirements:

> - `GaugeKit (= 0.4.0)` required by `Podfile`
> 
> None of your spec sources contain a spec satisfying the dependency: `GaugeKit (= 0.4.0)`.
> 
> You have either:
> - out-of-date source repos which you can update with `pod repo update`.
> - mistyped the name or version.
> - not added the source repo that hosts the Podspec to your Podfile.

**Comment by ugomarinelli** [comment]
Hi, 

I am facing the same issue, cannot install the 0.4.0 version, 

Thanks

**Comment by ugomarinelli** [comment]
I found why , in your podfile put this line instead : 

 pod 'GaugeKit', :git => 'https://github.com/skywinder/GaugeKit.git', :tag => '0.4.0'

I think the issue is, your pod version is outdated

**Comment by skywinder** [comment]
@ugomarinelli Thanks, indeed, pods didn't updated with latest release. Fixed  already. Now you can you it as usual.

**Comment by alexbartisro** [comment]
@skywinder   This issue still reproduces for me. I'm on pods 1.2.0-rc1 and ran pod repo update, but it still downloads  0.3.2

**Comment by skywinder** [comment]
@trusk89 ```pod search GaugeKit```

shows, that 0.4.0 is released. please, double check it.

```
GaugeKit (0.4.0)
   Kit for building custom gauges + easy reproducible Apple's style ring gauges.
   pod 'GaugeKit', '~> 0.4.0'
   - Homepage: https://github.com/skywinder/GaugeKit
   - Source:   https://github.com/skywinder/GaugeKit.git
   - Versions: 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.1, 0.1.0
   [master repo]
```

**Comment by ghost** [comment]
This issue still reproduces for me as well.

> GaugeKit (0.3.2)
>    Kit for building custom gauges + easy reproducible Apple's style ring gauges.
>    pod 'GaugeKit', '~> 0.3.2'
>    - Homepage: https://github.com/skywinder/GaugeKit
>    - Source:   https://github.com/skywinder/GaugeKit.git
>    - Versions: 0.3.2, 0.3.1, 0.3.0, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0,
>    0.1.1, 0.1.0 [master repo]

**Comment by skywinder** [comment]
I believe it's fixed already. please kindly check 👍

**Comment by Schteef** [comment]
*Hi @skywinder:*

*I'm trying to run Example in Xcode 9.4.1 on my iPhone 7+ (iOS 11.4.1) and I'm almost there - except I'm getting the error* **"App installation failed. Could not inspect the application package."** *right at the last step.*

*Here are the messages for my iPhone from the console just before the failed installation:* 



* **default	14:58:58.942412 -0700	installd**	com.stevedancho.GaugeKit:7:5:1:1:Start : Install (New)

* **default	14:58:58.942474 -0700	installd**	0x16d337000 -[MIFileManager itemDoesNotExistAtURL:]: Failed to determine if file:///private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.UKq6gZ/extracted/Example.app/Frameworks/GaugeKit.framework/Info.plist exists: Not a directory

* **default	14:58:58.942546 -0700	installd**	0x16d337000 MILoadInfoPlist: Failed to create CFBundle from URL file:///private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.UKq6gZ/extracted/Example.app/Frameworks/GaugeKit.framework/

* **default	14:58:58.942771 -0700	assertiond**	Client relinquished <BKTerminationAssertion: 0x10bd417e0; "FBSApplicationTerminationAssertion" (Unconditional); 47:(null) id:…31852A229370>

* **default	14:58:58.942835 -0700	assertiond**	-[BKAssertion dealloc] - <0x10bd417e0>

* **default	14:58:58.943583 -0700	installd**	0x16d337000 -[MIBundle _validateWithError:]: 38: Failed to load Info.plist from bundle at path /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.UKq6gZ/extracted/Example.app/Frameworks/GaugeKit.framework

* **default	14:58:58.943643 -0700	installd**	0x16d337000 -[MIInstaller performInstallationWithError:]: Preflight stage failed

* **default	14:58:58.965910 -0700	installd**	com.stevedancho.GaugeKit:7:5:2:0:Fail (End) : Install (New)

* **default	14:58:58.971078 -0700	lsd** com.stevedancho.GaugeKit:5:1:2:0:MobileInstallation returned nil for file:///var/mobile/Media/PublicStaging/Example.app/

* **default	14:58:58.971290 -0700	lsd** Sending applicationsDidFailToInstall: for <private>

* **error	14:58:58.971338 -0700	routined** LaunchServices observer: Apps Failed be installed: <private>

* **error	14:58:58.971428 -0700	nsurlsessiond**	LaunchServices observer: Apps Failed be installed: <private>

* **... lots more of these type error messages:**  Apps Failed be installed: <private> ...

* **default	14:58:58.972532 -0700	SpringBoard**	-[FBApplicationLibrary applicationsDidFailToInstall:] com.stevedancho.GaugeKit

* **error	14:58:58.972579 -0700	SpringBoard** Applications did fail to install: (
    "<LSApplicationProxy: 0x1313ec3e0> com.stevedancho.GaugeKit (null) <com.stevedancho.GaugeKit <INVALID >:0>"
) (appInfos: (null))

* **default	14:58:58.972707 -0700	streaming_zip_conduit** com.stevedancho.GaugeKit:5:1:2:0:_LSInstallationManager install:withError finished

* **default	14:58:58.972903 -0700	streaming_zip_conduit** dispatch_source_read_socket_block_invoke:312: Failed to install application at file:///var/mobile/Media/PublicStaging/Example.app/ : Error Domain=MIInstallerErrorDomain Code=35 "Failed to load Info.plist from bundle at path /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.UKq6gZ/extracted/Example.app/Frameworks/GaugeKit.framework" UserInfo={LegacyErrorString=PackageInspectionFailed, FunctionName=-[MIBundle _validateWithError:], SourceFileLine=38, NSLocalizedDescription=Failed to load Info.plist from bundle at path /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.UKq6gZ/extracted/Example.app/Frameworks/GaugeKit.framework}

*Any suggestions would be greatly appreciated -*
