### ISSUE TITLE
How run exaple

### ISSUE THREAD

**Issue by kezcol** [skywinder/GaugeKit#42]
Hey! How can i run Example on xcode 8? I have many errors when i try.

**Comment by skywinder** [comment]
Hi. What kind of errors?

**Comment by kezcol** [comment]
![zrzut ekranu 2016-10-05 o 15 33 07](https://cloud.githubusercontent.com/assets/13214293/19115190/4a7e8578-8b11-11e6-8588-7153cbfb93a6.png)

**Comment by kezcol** [comment]
![zrzut ekranu 2016-10-05 o 15 36 08](https://cloud.githubusercontent.com/assets/13214293/19115267/99fd19ca-8b11-11e6-9292-5db3f8ea5321.png)

**Comment by kezcol** [comment]
Im tried to install from cocoapods but then i got this
![zrzut ekranu 2016-10-05 o 15 33 07](https://cloud.githubusercontent.com/assets/13214293/19115382/09561718-8b12-11e6-9db8-10e63eff2ada.png)

**Comment by skywinder** [comment]
Seems this problems caused by last update to swift 3.
If you are running on Swift 2.x - please run last stable vesion on Swift 2: `0.3.2` https://github.com/skywinder/GaugeKit/tree/0.3.2

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
