### ISSUE TITLE
Set rate without animation

### ISSUE THREAD

**Issue by luismachado** [skywinder/GaugeKit#45]
Hi!

Is there anyway to set the rate without the gauge animating from the previous rate to the new one?

I'm asking this because, in my project, I'll be using the gauge multiple consecutive times, from 0 to X and when it reaches X I set it back to 0. However, as it animates the transition from X to 0 it doesn't looks to good.

Thanks for the work on the kit btw!

**Comment by skywinder** [comment]
Hi. please check demo project for animation example 👍

**Comment by skywinder** [comment]
You can set animation time to 0.
Feel free to reopen if you have any questions.
