### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by nikita-leonov** [skywinder/GaugeKit#46]
Is anyone working on Swift 3 support? If not I am ready to jump on this task.

**Comment by nikita-leonov** [comment]
It seems no source-code changes needed this time, only project file settings change.

**Comment by nikita-leonov** [comment]
After further investigation it seems nothing need to be done, just documentation need to be updated that current cocoapods seamlessly works with Swift 3 :) 🎉

**Comment by sdevo619** [comment]
I am actually having a bit of an issue with my Swift 3 project and wanted to know if you might be able to provide some insight. This issue I am seeing is a compiler waring message, which does not prevent the app from compiling and running, but I wanted to see if there is a way to fix whatever is causing the compiler warning message. This is the message I am seeing. There are a total of 116 compiler warnings for 4 gauges that are in the app I am building. Researched the error with no luck so far. Any ideas? So far the only thing I have done is create the views for the gauges, changed the class to Gauge, connected the outlets to the TableView Controller Custom Cell, and this is what I am seeing.

![screen shot 2017-02-17 at 2 07 41 am](https://cloud.githubusercontent.com/assets/7008354/23061253/ed7d81da-f4b5-11e6-9225-546bf3566f1c.png)
![screen shot 2017-02-17 at 1 59 58 am](https://cloud.githubusercontent.com/assets/7008354/23061261/f5e5a33e-f4b5-11e6-8a3d-d7c33c0f0c9c.png)

warning: IB Designables: Ignoring user defined runtime attribute for key path "borderWidth" on instance of "GaugeKit.Gauge". Hit an exception when attempting to set its value: [<GaugeKit.Gauge 0x7f98e5e7fb70> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key borderWidth.

warning: IB Designables: Ignoring user defined runtime attribute for key path "endAngle" on instance of "GaugeKit.Gauge". Hit an exception when attempting to set its value: [<GaugeKit.Gauge 0x7f98e5e7fb70> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key endAngle.

**Comment by nikita-leonov** [comment]
It seems IBDesignable related issue (http://stackoverflow.com/questions/26656400/uibutton-with-ib-designable-throws-runtime-attribute-warning-and-does-not-render), I am not using this feature of GaugeKit in my code, so do not have such warnings. Please, post results of your investigation here, so we can fix it.

**Comment by nikita-leonov** [comment]
ps closing this issue for now as there are no blocking issues with use of GaugeKIt with Swift 3.
