### ISSUE TITLE
Display half a circle

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [skywinder/GaugeKit#53]
Is it possible to create a gauge view that looks like this?

![screen shot 2017-09-06 at 9 57 25 am](https://user-images.githubusercontent.com/2551877/30096009-95438e92-92f3-11e7-9f8b-f60f4226ba30.png)

The circlular gauge type draws the full circle. Instead have a left/right type of gauge but horizontally?

**Comment by skywinder** [comment]
Hello.
We have a half gauge and full circle for now.
