### ISSUE TITLE
Can I add a circle at the tip of progress 

### ISSUE THREAD

**Issue by DivyaSaraswati** [skywinder/GaugeKit#58]
![screen shot 2017-12-18 at 4 33 55 pm](https://user-images.githubusercontent.com/34904871/34400361-7358efea-ebb6-11e7-8553-bbc3080ee262.png)

can I made something like this with this library

**Comment by skywinder** [comment]
There is no implementation of this option.
I'd be more than happy to merge a PR adding this feature; it seems like it would be useful for sure 👍

**Comment by jimijon** [comment]
was this ever worked on?

**Comment by skywinder** [comment]
Same state: There is no such feature.
