### ISSUE TITLE
IBDesignable build fails when making a UIView of class Gauge

### ISSUE THREAD

**Issue by jfosterdavis** [skywinder/GaugeKit#59]
I am just trying to get a "Hello World" with GaugeKit.  Creating a CocoaPod by following guide at (https://developerslogblog.wordpress.com/2017/05/14/swiff-3-reusable-components-using-xib-files-and-the-interface-builder/)

When I add a UIView to my storyboard (or .xib) that is IBDesignable I get "build failed."

![screen shot 2018-01-20 at 11 53 26 am](https://user-images.githubusercontent.com/6314219/35185862-9722211a-fdd8-11e7-8081-70a1f1c227e7.png)

When adding to the storyboard and attempting to build I see a #selector issue: "Argument of '#selector' refers to instance method 'updateProgress' that is not exposed to Objective-C"

![screen shot 2018-01-20 at 11 51 11 am](https://user-images.githubusercontent.com/6314219/35185871-ba8a7d14-fdd8-11e7-8d0e-5945b2072d4a.png)

Running Xcode 9.2, Swift 3.x.  My project commit that holds this error: (https://github.com/jfosterdavis/ZMUtilityAppFramework/commit/f059d2bfc6cb9533140325313a037a6ec3959554)

**Comment by jfosterdavis** [comment]
When I unlocked the GaugeKit file and performed the Xcode-recommended fix action (you can see this recommended fix action in the image in my OP), I got a (possibly unrelated) build error about another dependency. 

I ran `pod update` on my pods and then the project built successfully and I see the "default" gauge.
![screen shot 2018-01-20 at 12 07 34 pm](https://user-images.githubusercontent.com/6314219/35185992-e1ed8c46-fdda-11e7-853c-3ed1048c80b3.png)

I am not pushing GaugeKit files in my repo, but here is the commit where I see it working.  Appears only change was in my pod .pbxproj  (https://github.com/jfosterdavis/ZMUtilityAppFramework/commit/cfce91f4868e86a2a63ccfe386cf21e57103ecc3)

**Comment by skywinder** [comment]
fixed too :+1:
