### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by argomis** [skywinder/GaugeKit#60]
Hello, thanks for this very useful project.
For making it compatible with Swift 4 you just needs to do the following modification :

In file Gauge+Animations.swift
the function:
func updateProgress(_ timer: Timer) -> Void 
needs to have @objc to respond to the selector:
@objc func updateProgress(_ timer: Timer) -> Void

**Comment by gholias** [comment]
Im also having the same issue

**Comment by gholias** [comment]
I've created a fork and fixed the issue
  pod 'GaugeKit', :git => 'https://github.com/gholias/GaugeKit.git', :branch => 'master'

**Comment by piperpilot** [comment]
@gholias seems the version that you pushed isn't properly signed.  It won't let me use it in my swift4 based project.  Is there an admin that can possibly merge the changes needed so this can continue to be used?  Looks like a great component, but currently not usable.

Nevermind...I seem to have gotten it working now.

**Comment by skywinder** [comment]
Thanks, @gholias! would you like to make a PR with this feature?

**Comment by skywinder** [comment]
Fixed!
