### ISSUE TITLE
View has lost track of its superview

### ISSUE THREAD

**Issue by sashberd** [skywinder/GaugeKit#61]
Hi

Great project guys!!!

I am trying to add labels of values on the gauge, but when I add the label I got next error:

`View has lost track of its superview, most likely through unsupported use of CALayer API on the view's layer. If this isn't a crash yet, it will be in the near future. `

Any suggestions?

**Comment by skywinder** [comment]
Long time no see :)
I hope the problem is solved already. if not:  Please provide a code example to this issue
