### ISSUE TITLE
Support for iOS 12 and Xcode 10 beta

### ISSUE THREAD

**Issue by costaneto222** [skywinder/GaugeKit#62]
I know that is too early to ask, but we are with a little problem on GaugeKit in iOS 12 using Xcode 10 beta. The GaugeKit was working fine in my app until the last version, but when I updated to iOS 12 and Xcode 10, the app doesn't compile anymore.

This is what I receive from xcode.
Showing Recent Messages
:-1: Multiple commands produce '/Users/…/Library/Developer/Xcode/DerivedData/…/Build/Products/Debug-iphoneos/GaugeKit/GaugeKit.framework/Info.plist':
1) Target 'GaugeKit' has copy command from '/Users/…/Desktop/…/Pods/GaugeKit/GaugeKit/Info.plist' to '/Users/…/Library/Developer/Xcode/DerivedData/…/Build/Products/Debug-iphoneos/GaugeKit/GaugeKit.framework/Info.plist'
2) Target 'GaugeKit' has process command with input '/Users/…/Desktop/…/Pods/Target Support Files/GaugeKit/Info.plist'

Could you help me?

**Comment by akshya672222** [comment]
@costaneto222  did you found any solution?

**Comment by costaneto222** [comment]
Not yet =/
I'm back in Xcode 9 until this problem was resolved.

**Comment by akshya672222** [comment]
I found something that might help:
https://stackoverflow.com/a/51089254/3824808

**Comment by costaneto222** [comment]
Great!
It apparently solved the GaugeKit problem, but now I'm facing troubles with ZenDesk SDK haha
Thank you @akshya672222
