### ISSUE TITLE
Gauge+Animations updateProgress not exposed to Objective-C

### ISSUE THREAD

**Issue by jfosterdavis** [skywinder/GaugeKit#63]
```
pod spec lint

 -> ZMAppFoundation (0.1.5)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | xcodebuild:  GaugeKit/GaugeKit/Gauge+Animations.swift:22:23: error: argument of '#selector' refers to instance method 'updateProgress' that is not exposed to Objective-C
    - NOTE  | xcodebuild:  GaugeKit/GaugeKit/Gauge+Animations.swift:32:10: note: add '@objc' to expose this instance method to Objective-C

Analyzed 1 podspec.
```
I have a cocoa pod that uses gauge kit as a dependency (https://github.com/jfosterdavis/ZMAppFoundation/tree/release-0.1.5).  When I am doing local development I change line Gauge+Animations.swift:32:10 from:
`func updateProgress(_ timer: Timer) -> Void {`
to
`@objc func updateProgress(_ timer: Timer) -> Void {`

**Comment by jfosterdavis** [comment]
It looks like this is corrected in your swift-4 branch?

**Comment by skywinder** [comment]
fixed in latest versions
