### ISSUE TITLE
CocoaPods failed: required code signature missing for 'GaugeKit.framework'

### ISSUE THREAD

**Issue by Silvia4** [skywinder/GaugeKit#65]
Hi,
I would love to use your beautiful control, but I can't get it to work. I used CocoaPods for importing it, then add @objc in the method requested for  swift 4 support. But then I get this error:

../Main.storyboard: error: IB Designables: Failed to render and update auto layout status for ProvaViewController (Rn0-yv-HO4): dlopen(GaugeKit.framework, 1): no suitable image found.  Did find: GaugeKit.framework: required code signature missing for 'GaugeKit.framework'

Can you help me please?

**Comment by aakankshsingh13** [comment]
I have the same problem.

**Comment by skywinder** [comment]
Hello. I didn’t try to use it with obj-c. Tbh, have more important  projects and can’t debug it right now. Please let me know if you find any solution. 👍

**Comment by skywinder** [comment]
fixed in latest versions
