### ISSUE TITLE
How can we make the gauge as in following image?

### ISSUE THREAD

**Issue by njawahire** [skywinder/GaugeKit#69]
![Screenshot 2019-03-26 at 5 07 48 PM](https://user-images.githubusercontent.com/8917350/54994250-d28de680-4fe9-11e9-8aba-76fc701fec3d.png)

Please let me know if it is possible with this kit.... If not please guide me how can I achieve it

**Comment by ghost** [comment]
+1

**Comment by njawahire** [comment]
I solved my problem with the help of this snippet. Take a look at it. It might help you. 
https://stackoverflow.com/a/55420503

**Comment by skywinder** [comment]
@njawahire Thanks for the update. If you would like to implement it in Swift - I will be happy to merge PR with this styled Gauge!
👍
