### ISSUE TITLE
Implement a maxValue

### ISSUE THREAD

**Issue by ghost** [skywinder/GaugeKit#7]
Hey, first of all thank you for this project.

What I need you to help me think is how can I implement a maxValue feature like a UISlider so if I have a timer it goes and finish at the same time as the timer or if there's a way already can you be so kind to explain how to implement it because rate works perfectly but I need to increment de Gauge proportionally a Timer I have.

Let me know if you need more context and thank you very much for your help.

**Comment by skywinder** [comment]
@BenAraqve Hi! Thanks! I will try to provide some animation examples soon.

**Comment by ghost** [comment]
Meanwhile, can you help me understand the part of the code that makes the logic of rate to increment by percentage and how can I change the scale of the percentage: 

What do you mean by this: "/// Percentage of filling Gauge: 0..10" in this part of the code:

/// Percentage of filling Gauge: 0..10
    @IBInspectable public var rate: CGFloat = 9 {
        didSet {
            updateLayerProperties()
        }
    }
    @IBInspectable var isCircle: Bool = false {
        didSet {
            updateLayerProperties()
        }
    }
    @IBInspectable var lineWidth: CGFloat = 15.0 {
        didSet {
            updateLayerProperties()
        }
    }

And which is the code for the multiplication of the rate, is this one?:

```
            let percanage = rate / 20 % 0.5
            ringLayer.strokeEnd = (rate >= 10 ? 0.5 : percanage + ((rate != 0 && percanage == 0) ? 0.5 : 0))
```

Thank you very much, I'm actually in a hurry here but of course I dont mean to dispose of your time BUT if you can help that would be great.

**Comment by skywinder** [comment]
It's a good idea to implement multiplayer factor parameter. I also thinking
about it. Please, wait for new version. I will release it today with big
code improvements and implement this parameter also.

Bdw, code, that you pointed out is adjustment for correct presentation of
half gauges.

All wishes and suggestions are very welcome!

**Comment by ghost** [comment]
Wow, thank you very much. I appreciate that.

I'll be waiting for this new version.

**Comment by skywinder** [comment]
Done!

bdw: about animation, try to use `animateWithDuration` method like:

```
UIView.animateWithDuration(1 animations: { () -> Void in
                                                    self.myGauge.rate = newRateValue
                                                })
```
