### ISSUE TITLE
How does one rotate the .half gauge?

### ISSUE THREAD

**Issue by jimijon** [skywinder/GaugeKit#81]
I put in 180 in rotate in IB but nothing seems to change on the view. How can I make it .top or .bottom instead of .left or .right?

**Comment by skywinder** [comment]
Hi. It's rotating. but the formula is a bit inconvenient, (probably it's better to change into degrees?)
```
        gaugeLayer = getGauge(rotate / 10 * Double.pi)
```
<img width="464" alt="Screenshot 2020-02-16 at 14 28 50" src="https://user-images.githubusercontent.com/3356474/74600767-a8915700-50c8-11ea-84b6-3196e59ad7fd.png">

so to rotate on 180 you have to set value 10.

**Comment by skywinder** [comment]
Feel free to reopen the issue, if you still need help. 👍
