### ISSUE TITLE
start and stop points

### ISSUE THREAD

**Issue by jimijon** [skywinder/GaugeKit#82]
Is it possible to smaller arcs? I want to try to do a series of arcs on the same path. First segment say 10degrees, then a gap, then a new segment of 40degress, then a small gap and then another segment.

Or simply point me to how to creat say a 20 degree arc. Both ends need to be rounded so I can’t just turn it white for thev160 degrees left. 

Thank you

**Comment by jimijon** [comment]
OK, I see strokeEnd,,, but that gets calculated. Yet it is a constant in CAShapeLayer.getOval....

Any reason this is such?

**Comment by skywinder** [comment]
Hello, @jimijon. It was just a first solution, that comes to my mind. If you know a better and more flexible way to implement this -  I would be happy to merge this! 🙌

**Comment by jimijon** [comment]
Simple question. Why is strokeend hardcoded 0.25?

**Comment by skywinder** [comment]
TBH, I don't remember, if they're a special point for this. ¯\_(ツ)_/¯ 
It was my pet project to learn swift 5 years ago.
Since it still works.. I didn't change I for all these years.
 So feel free to play around with it 🚀
