### ISSUE TITLE
Arrow indicator for half gauge chart?

### ISSUE THREAD

**Issue by nastasiupta** [skywinder/GaugeKit#83]
Instead of displaying the background color with opacity and the current value without opacity, I would like to display the whole gauge chart with gradient colors, and an arrow indicator of the current value. For example, if I have 0 to 10, and the current value is 7, I would like to indicate the value of 7 with an arrow indicator. Any advice on that?
[](url)
![apps 219 1d604ee5-95ff-40af-9a99-e465be8ff935 0643708b-62c6-4a99-86e0-b47cec4a76b8 65a07479-d5dc-4d45-ad18-07485d8a0301](https://user-images.githubusercontent.com/13376064/99674828-38609900-2a7f-11eb-9f72-dfb34441b0cc.png)

**Comment by skywinder** [comment]
There is no such feature yet. I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍
